apiVersion: v1
kind: Pod
metadata:
  name: myapps
  namespace: database
  labels:
    app: my1stapps
spec: 
  containers:
  - name: myapps
    image: hujefakazi/batch2k26:httpd-v
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80   
---
apiversion: v1
kind: Namespace
metadata:
  name: database
