apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: database
  labels:
    app: my1stapp
spec:
  containers:
  - name: myapp
    image: mariadb
    env:
    - name: MARIADB_ROOT_PASSWORD
      valueFrom:
         secretKeyRef:
           key: password
    - name: mydepartment
      valueFrom:
         configMapKeyRef:
           name: myvariables
           key: mydepartment 
    ports:
      - containerPort: 80