- name: this playbook for apache2 installation
  hosts: all
  tasks:
    - name: update
      shell:
        cmd: apt-get update
    - name: install apache2
      apt:
        name: apache2
        state: latest
      ignore_errors: true
       
    - name: install httpd
      yum:
        name: httpd
        state: latest