- name: package installation
  hosts: all
  tasks:
    - name: install httpd
      package: 
        name: httpd
        state: latest
      when: ansible_distribution == "RedHat"
    - name: install apache2
      package:
        name: apache2
        state: present 
      when: ansible_distribution == "debian"  

    - name: start service
      systemd: 
        name:
        state: started
        enabled: true
      when: ansible_distribution == "debian"
    - name: start httpd
      service: 
        name: httpd
        state: started
      when: ansible_distribution == "RedHat"

