- name: this is variable learning
  hosts: all
  var:
    animal: "tiger"
  tasks:
    - name: print animal 1
      debug:
        msg: "{{animal}}"
    - name: print animal 2
      debug:
        msg: "{{animal}}"
    - name: print aniaml 3
      debug:
        msg: "{{animal}}"
             